PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX sio: <http://semanticscience.org/resource/>

SELECT DISTINCT ?materialname ?ERM ?ke ?mie ?mietitle ?aop ?aotitle WHERE {
  ?s a obo:CHEBI_59999 ;
   	dcterms:identifier ?ERM ;
   	dcterms:title ?materialname ;
   	sio:SIO_000001 ?ke .
  FILTER (!regex(?materialname, "microparticle|macroparticle", "i"))
  SERVICE <https://aopwiki.rdf.bigcat-bioinformatics.org/sparql> {
	?aop aopo:has_key_event ?ke ;
     	aopo:has_molecular_initiating_event ?mie ;
     	aopo:has_adverse_outcome ?ao .
	?mie dc:title ?mietitle .
	?ao dc:title ?aotitle .
	FILTER CONTAINS(?mietitle, "DNA")
  }
}
