PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

select distinct ?materialtype (count (distinct ?ID AS ?n)) (GROUP_CONCAT(distinct ?materialname;SEPARATOR=", ") AS ?materialnames)  where { 
    ?s a obo:CHEBI_59999; 
    dcterms:identifier ?ID ; 
    rdfs:label ?materialname ; 
    dcterms:type ?materialtype ; 
    dcterms:source ?source.
}
